# Generated by Django 5.1.5 on 2025-01-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apaeropuerto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'administardor'), (2, 'pasajero'), (3, 'gerente')], default=1),
        ),
    ]
