# Generated by Django 5.1.2 on 2024-10-18 21:49

import apaeropuerto.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ES', 'Aeropuerto Adolfo Suárez Madrid-Barajas'), ('FR', 'Aeropuerto Charles de Gaulle'), ('IT', 'Aeropuerto Internacional Leonardo da Vinci'), ('DE', 'Aeropuerto de Berlín-Tegel'), ('PT', 'Aeropuerto de Lisboa'), ('NL', 'Aeropuerto de Ámsterdam-Schiphol'), ('BE', 'Aeropuerto de Bruselas-Zaventem'), ('SE', 'Aeropuerto de Estocolmo-Arlanda'), ('AT', 'Aeropuerto Internacional de Viena'), ('CH', 'Aeropuerto de Ginebra')], max_length=100, verbose_name='Aeropuerto')),
                ('ciudades', models.CharField(choices=[('ES', 'Madrid'), ('FR', 'París'), ('IT', 'Roma'), ('DE', 'Berlín'), ('PT', 'Lisboa'), ('NL', 'Ámsterdam'), ('BE', 'Bruselas'), ('SE', 'Estocolmo'), ('AT', 'Viena'), ('CH', 'Ginebra')], max_length=100)),
                ('pais', models.CharField(choices=[('ES', 'España'), ('FR', 'Francia'), ('IT', 'Italia'), ('DE', 'Alemania'), ('PT', 'Portugal'), ('NL', 'Países Bajos'), ('BE', 'Bélgica'), ('SE', 'Suecia'), ('AT', 'Austria'), ('CH', 'Suiza')], max_length=100)),
                ('capacidad_maxima', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('JE', 'Jefe'), ('EM', 'Empleado')], max_length=2)),
                ('fecha_contratacion', models.DateField()),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, validators=[apaeropuerto.models.validar_dominio_email])),
                ('telefono', models.CharField(blank=True, max_length=9, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(message='El número de teléfono debe tener exactamente 9 dígitos.', regex='^\\d{9}$')])),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('distancia', models.FloatField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='apaeropuerto.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('duracion', models.IntegerField()),
                ('aeropuerto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo_dia', models.IntegerField(db_column='veces_volado_dia', error_messages={'blank': 'Este campo no puede estar vacío.'})),
                ('hora_salida', models.DateTimeField()),
                ('hora_llegada', models.DateTimeField()),
                ('volando', models.BooleanField()),
                ('duracion', models.DurationField(editable=False)),
                ('aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('clase', models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'First Class'), ('P', 'Premium Economy'), ('L', 'Luxury'), ('S', 'Standard'), ('H', 'Hybrid'), ('X', 'Extra Legroom'), ('R', 'Regional'), ('C', 'Charter')], max_length=1)),
                ('precio', models.FloatField()),
                ('posicion', models.IntegerField()),
                ('pasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('estado', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal')], default='tarjeta', max_length=10)),
                ('estado_de_pago', models.BooleanField(default=False)),
                ('pasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.vuelo')),
            ],
        ),
        migrations.AddField(
            model_name='pasajero',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.vuelo'),
        ),
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('dimensiones', models.CharField(max_length=50)),
                ('tipo_material', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=50)),
                ('pasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Aerolínea operadora')),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_fundacion', models.DateField()),
                ('pais', models.CharField(choices=[('ES', 'España'), ('EN', 'Inglaterra'), ('FR', 'Francia'), ('IT', 'Italia')], max_length=2)),
                ('aeropuerto', models.ManyToManyField(to='apaeropuerto.aeropuerto')),
                ('vuelo', models.ManyToManyField(to='apaeropuerto.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='VueloAerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateTimeField()),
                ('estado', models.TextField()),
                ('clase', models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'First Class'), ('P', 'Premium Economy'), ('L', 'Luxury'), ('S', 'Standard'), ('H', 'Hybrid'), ('X', 'Extra Legroom'), ('R', 'Regional'), ('C', 'Charter')], max_length=1)),
                ('numero_de_vuelos', models.IntegerField(default=5)),
                ('aerolinea', models.ManyToManyField(to='apaeropuerto.aerolinea')),
                ('vuelo', models.ManyToManyField(to='apaeropuerto.vuelo')),
            ],
        ),
    ]
