# Generated by Django 5.1.2 on 2024-10-30 08:30

import apaeropuerto.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Aeropuerto')),
                ('ciudades', models.CharField(choices=[('ES', 'Madrid'), ('FR', 'París'), ('IT', 'Roma'), ('DE', 'Berlín'), ('PT', 'Lisboa'), ('NL', 'Ámsterdam'), ('BE', 'Bruselas'), ('SE', 'Estocolmo'), ('AT', 'Viena'), ('CH', 'Ginebra')], default='ES', max_length=2)),
                ('pais', models.CharField(choices=[('ES', 'España'), ('FR', 'Francia'), ('IT', 'Italia'), ('DE', 'Alemania'), ('PT', 'Portugal'), ('NL', 'Países Bajos'), ('BE', 'Bélgica'), ('SE', 'Suecia'), ('AT', 'Austria'), ('CH', 'Suiza')], default='ES', max_length=2)),
                ('capacidad_maxima', models.IntegerField(default=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, validators=[apaeropuerto.models.validar_dominio_email])),
                ('telefono', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Aerolínea operadora')),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_fundacion', models.DateField(auto_now_add=True)),
                ('pais', models.CharField(choices=[('ES', 'España'), ('EN', 'Inglaterra'), ('FR', 'Francia'), ('IT', 'Italia')], default='ES', max_length=2)),
                ('aeropuerto', models.ManyToManyField(related_name='aerolinea_de_aeropuerto', to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoAeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('años_trabajados', models.IntegerField(default=0, verbose_name='Años Trabajado')),
                ('aeropuerto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('dimensiones', models.CharField(max_length=50)),
                ('tipo_material', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=50)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipaje_pasajero', to='apaeropuerto.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('documento_identidad', models.CharField(max_length=9, unique=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50)),
                ('vivienda', models.CharField(blank=True, max_length=50)),
                ('pasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pasajero_datos', to='apaeropuerto.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('duracion_servicio', models.TimeField()),
                ('añadido', models.CharField(max_length=100)),
                ('aeropuerto', models.ManyToManyField(related_name='servicio_aeropuerto', to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('JE', 'Jefe'), ('EM', 'Empleado')], default='EM', max_length=2)),
                ('fecha_contratacion', models.DateField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_servicio', to='apaeropuerto.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.DateTimeField(error_messages={'blank': 'Este campo no puede estar vacío.'})),
                ('hora_llegada', models.DateTimeField(error_messages={'blank': 'Este campo no puede estar vacío.'})),
                ('estado', models.BooleanField(db_column='Volando')),
                ('duracion', models.DurationField(editable=False)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_de_destino', to='apaeropuerto.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_de_origen', to='apaeropuerto.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo_descueto', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('efectivo', 'Efectivo'), ('paypal', 'PayPal')], default='tarjeta', max_length=10)),
                ('estado_de_pago', models.BooleanField(default=False)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_pasajero', to='apaeropuerto.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelo_reserva', to='apaeropuerto.vuelo')),
            ],
        ),
        migrations.AddField(
            model_name='pasajero',
            name='vuelo',
            field=models.ManyToManyField(related_name='vuelo_pasajero', to='apaeropuerto.vuelo'),
        ),
        migrations.CreateModel(
            name='EstadisticasVuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estadisticas', models.DateField(auto_now_add=True)),
                ('numero_asientos_vendidos', models.IntegerField(default=0)),
                ('numero_cancelaciones', models.IntegerField(default=0)),
                ('feedback_pasajeros', models.TextField(blank=True)),
                ('vuelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vuelo_datos', to='apaeropuerto.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'First Class'), ('P', 'Premium Economy'), ('L', 'Luxury'), ('S', 'Standard'), ('H', 'Hybrid'), ('X', 'Extra Legroom'), ('R', 'Regional'), ('C', 'Charter')], default='E', max_length=1)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('posicion', models.CharField(choices=[('P', 'Pasillo'), ('M', 'Medio'), ('V', 'Ventana')], max_length=1)),
                ('sistema_entretenimiento', models.BooleanField()),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pajarelo_asiento', to='apaeropuerto.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asiento_vuelo', to='apaeropuerto.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='VueloAerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateTimeField(null=True)),
                ('estado', models.TextField()),
                ('clase', models.CharField(choices=[('E', 'Economy'), ('B', 'Business'), ('F', 'First Class'), ('P', 'Premium Economy'), ('L', 'Luxury'), ('S', 'Standard'), ('H', 'Hybrid'), ('X', 'Extra Legroom'), ('R', 'Regional'), ('C', 'Charter')], default='E', max_length=1)),
                ('incidencias', models.CharField(max_length=100)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aerolinea_media_aerolinea', to='apaeropuerto.aerolinea')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelo_media_aerolinea', to='apaeropuerto.vuelo')),
            ],
        ),
        migrations.AddField(
            model_name='vuelo',
            name='aerolinea',
            field=models.ManyToManyField(related_name='vuelo_aerolinea', through='apaeropuerto.VueloAerolinea', to='apaeropuerto.aerolinea'),
        ),
    ]
