# Generated by Django 5.1.2 on 2024-11-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apaeropuerto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vueloaerolinea',
            name='fecha_operacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
