# Generated by Django 5.1.2 on 2024-11-04 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apaeropuerto', '0002_alter_vueloaerolinea_fecha_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('C', 'CAIXA'), ('B', 'BBVA'), ('U', 'UNICAJA'), ('I', 'ING')], max_length=1)),
                ('pasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banco_pasajero', to='apaeropuerto.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=100)),
                ('fecha_voto', models.DateTimeField(default=django.utils.timezone.now)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto_pasajero', to='apaeropuerto.pasajero')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto_vuelo', to='apaeropuerto.vuelo')),
            ],
        ),
    ]
